# Change these first
owner: okkilee # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: hub.cid.agilent.com
    url: https://hub.cid.agilent.com
  - name: hub for stg-51
    url: https://hub.stg-51.aws.agilent.com
  - name: hub for tst-51
    url: https://hub.tst-51.aws.agilent.com
  - name: Jenkins pipeline
    url: https://jenkins.prd-51.aws.agilent.com/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.pvl.pub
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: This is a demo status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
