# Change these first
owner: okkilee # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Hub.cid.agilent.com
    url: https://hub.cid.agilent.com  - name: Jenkins Stg-51
  - name: Hub for Stg-51
    url: https://hub.stg-51.aws.agilent.com
  - name: Jenkins Prd-51
      url: https://jenkins.prd-51.aws.agilent.com/login
  - name: Jenkins Stg-51
    url: https://jenkins.stg-51.aws.agilent.com/login
  - name: pvl.pub
    url: https://up.pvl.pub

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.pvl.pub
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
